### ISSUE TITLE
cockpit.socket should be enabled/started, not cockpit.service

### ISSUE THREAD

**Issue by mvollmer** [linux-system-roles/cockpit#1]
https://github.com/linux-system-roles/cockpit/blob/68c8e5b432680c9b590207caef3e4a038883b1bf/tasks/main.yml#L12

I think the role starts and enables the cockpit.service unit, not cockpit.socket.  Cockpit is usually socket activated.

**Comment by tabowling** [comment]
Resolved in v0.3.1. Pushed to Galaxy.
